import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'yegor' at '2/24/16 3:19 AM' with Gradle 2.6
 *
 * @author yegor, @date 2/24/16 3:19 AM
 */
public class LibraryTest {
	@Test
	public void testSomeLibraryMethod() {
		// Library classUnderTest = new Library();
		// assertTrue("someLibraryMethod should return 'true'",
		// classUnderTest.someLibraryMethod());
	}
}
